semver: 1.2.0
version: '{semver}.{build}'
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{semver}'
  assembly_file_version: '{semver}'
  assembly_informational_version: '{semver}'
before_build:
- ps: nuget restore RoslynAnalyzers.sln
build:
  project: RoslynAnalyzers.sln
  publish_nuget: false
  publish_nuget_symbols: false
  use_snupkg_format: true
  parallel: true
  verbosity: minimal
artifacts:
- path: 'AssignAll\AssignAll\bin\Release\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: kx5RD9/LCY88bhFpoIasCPt3bJFnkhAG+LLk/JhS+s84OOYWYXthpr148JhsIXjr
  on:
    branch: master