version: 1.1.0.{build}
image: Visual Studio 2019
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore RoslynAnalyzers.sln
build:
  project: RoslynAnalyzers.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: kx5RD9/LCY88bhFpoIasCPt3bJFnkhAG+LLk/JhS+s84OOYWYXthpr148JhsIXjr
  on:
    branch: master