version: 1.5.0.{build}
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: 1.5.0
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: nuget restore RoslynAnalyzers.sln
build:
  project: RoslynAnalyzers.sln
  parallel: true
  verbosity: minimal
# Nuget is automatically built when building AssignAll project.
artifacts:
- path: 'AssignAll\AssignAll\bin\Release\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: kx5RD9/LCY88bhFpoIasCPt3bJFnkhAG+LLk/JhS+s84OOYWYXthpr148JhsIXjr
  on:
    branch: master